---

- name: Install mysql packages
  apt: 
    name: "{{ mysql_packages }}"
    state: present
    update_cache: yes

- name: Copy mysql configuration file
  template:
    src: mysqld.cnf.j2
    dest: "{{ mysql_conf_dir }}/mysql.conf.d/mysqld.cnf"
  notify: restart mysql

- name: Start mysql service
  service: 
    name: mysql
    state: started
    enabled: yes

- name: update mysql root password for all root accounts
  mysql_user:
    name: root
    password: "{{ mysql_root_db_pass }}"
    host: "{{ item }}"
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
  when: ansible_hostname == 'localhost'

- name: update mysql root password for all root accounts
  mysql_user:
    name: root
    password: "{{ mysql_root_db_pass }}"
    host: "{{ item }}"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  when: ansible_hostname != 'localhost'


- name: Copy .my.cnf file with password credentials
  template: 
    src: .my.cnf.j2
    dest: ~/.my.cnf
    mode: 0600
  notify: restart mysql

- name: Ensure anonymus users are not in the db
  mysql_user: 
    name: ''
    host: "{{ item }}"
    state: absent
  with_items: 
    - localhost
    - "{{ ansible_hostname }}"

- name: Remove the test database
  mysql_db:
    name: test
    state: absent

- name: Create databases
  mysql_db:
    name: "{{ item.name }}"
    state: present
  with_items: "{{ mysql_db }}"
  when: mysql_db | lower() != none

- name: Create db users
  mysql_user: 
    name: "{{ item.name }}"
    password: "{{ item.pass }}"
    priv: "{{ item.priv }}"
    state: present
    host: "%"
  with_items: "{{ mysql_users }}"


...
