---  
- hosts: localhost  
  connection: local  
  gather_facts: False    
  vars:  
    region: eu-west-1
  tasks: 

- name: Provision a EC2 instances
  ec2_instance:
    name: web-test-ansible
    status: present
    key_name: key_ansible
    region: "{{ region }}"
    vpc_subnet_id: "{{ subnet_id }}"
    security_group: sg_webservertest
    instance_type: t2.micro
    image_id: "{{ ami_id }}"
    wait: True
    network:
      assign_public_ip: yes
    register: ec2

- name: Wait for ssh to come up
  wait_for: hosts={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
  with_items: '{{ ec2.instances }}'