---  
- hosts: localhost  
  connection: local  
  gather_facts: False    
  vars:  
    region: eu-west-1
  tasks:  
    - name: create VPC
      ec2_vpc_net:
        name: test-vpc
        cidr_block: 10.0.0.0/16
        region: "{{ region }}"
      register: vpc
      
    - name: "set fact: VPC ID"
      set_fact:
        vpc_id: "{{ vpc.vpc.id }}"