---
- hosts: webapps
  become: yes
  gather_facts: False
  tasks:
          - name: Install httpd service
            yum:
                    name: httpd
                    state: latest

          - name: Start httpd service
            service:
                    name: httpd
                    state: started

