---
- hosts: all
  become: yes
  remote_user: ec2-user
  gather_facts: False
  tasks:
          - name: Install httpd service
            yum:
                    name: httpd
                    state: latest

          - name: Start httpd service
            service:
                    name: httpd
                    state: started

