---

- name: Ensure Apache is installed.
  apt: 
    name: "{{ apache_packages }}" 
    state: present

- name: Enable Apache mods.
  file:
    src: "{{ apache_server_root }}/mods-available/{{ item }}"
    dest: "{{ apache_server_root }}/mods-enabled/{{ item }}"
    state: link
    force: yes
  with_items: "{{ apache_mods_enabled }}"
  notify: restart apache

- name: Add apache vhosts configuration.
  template:
    src: "{{ apache_vhosts_template }}"
    dest: "{{ apache_conf_path }}/sites-available/{{ apache_vhosts_filename }}"
    owner: root
    group: root
    mode: 0644
  notify: restart apache

- name: Add vhost symlink in sites-enabled.
  file:
    src: "{{ apache_conf_path }}/sites-available/{{ apache_vhosts_filename }}"
    dest: "{{ apache_conf_path }}/sites-enabled/{{ apache_vhosts_filename }}"
    state: link
  notify: restart apache

- name: Remove default vhost in sites-enabled.
  file:
    path: "{{ apache_conf_path }}/sites-enabled/000-default.conf"
    state: absent
  notify: restart apache
  when: apache_remove_default_vhost

- name: Ensure Apache has selected state and enabled on boot.
  service:
    name: apache2
    state: started
    enabled: yes
